# Generated by Django 5.2.4 on 2025-08-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), (None, 'N/A')], default=None, max_length=20, null=True),
        ),
    ]
