# Generated by Django 5.2.4 on 2025-08-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_about_user_account_type_user_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
    ]
